from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt


FloatArray = npt.NDArray[np.float64]
IndexArray = npt.NDArray[np.int64]


@dataclass(slots=True)
class Mesh:
    name: str
    vertices: FloatArray
    faces: IndexArray


def _face_index(token: str, vertex_count: int) -> int:
    raw = int(token.split("/", 1)[0])
    index = raw - 1 if raw > 0 else vertex_count + raw
    if index < 0 or index >= vertex_count:
        raise ValueError(f"OBJ vertex index {raw} is out of range")
    return index


def read_obj(path: Path) -> Mesh:
    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[int, int, int]] = []

    with path.open("r", encoding="utf-8-sig") as stream:
        for line_number, line in enumerate(stream, start=1):
            fields = line.split()
            if not fields or fields[0].startswith("#"):
                continue
            if fields[0] == "v":
                if len(fields) < 4:
                    raise ValueError(f"{path}:{line_number}: incomplete vertex")
                vertices.append((float(fields[1]), float(fields[2]), float(fields[3])))
            elif fields[0] == "f":
                if len(fields) < 4:
                    raise ValueError(f"{path}:{line_number}: face has fewer than three vertices")
                polygon = [_face_index(token, len(vertices)) for token in fields[1:]]
                for index in range(1, len(polygon) - 1):
                    faces.append((polygon[0], polygon[index], polygon[index + 1]))

    vertex_array = np.asarray(vertices, dtype=np.float64)
    face_array = np.asarray(faces, dtype=np.int64)
    if vertex_array.ndim != 2 or vertex_array.shape[1:] != (3,):
        raise ValueError(f"{path}: no valid vertices")
    if face_array.ndim != 2 or face_array.shape[1:] != (3,):
        raise ValueError(f"{path}: no valid triangle faces")
    if not np.isfinite(vertex_array).all():
        raise ValueError(f"{path}: non-finite vertex coordinate")
    return Mesh(path.name, vertex_array, face_array)


def write_obj(path: Path, mesh: Mesh, comments: list[str] | None = None) -> None:
    with path.open("w", encoding="ascii", newline="\n") as stream:
        stream.write("# Generated by PQSSProxyMesh ConservativeOuter\n")
        for comment in comments or []:
            stream.write(f"# {comment}\n")
        stream.write(f"# Vertices {len(mesh.vertices)}\n")
        stream.write(f"# Faces {len(mesh.faces)}\n")
        stream.write("g proxy\n")
        for vertex in mesh.vertices:
            stream.write(f"v {vertex[0]:.17g} {vertex[1]:.17g} {vertex[2]:.17g}\n")
        for face in mesh.faces:
            stream.write(f"f {face[0] + 1} {face[1] + 1} {face[2] + 1}\n")
