param(
    [string]$Executable = "$PSScriptRoot\..\build\Release\pqss-primitive-mesh-analyze.exe",
    [string]$InputRoot = "$PSScriptRoot\..\test_data\real_scene\source_pool",
    [string]$OutputRoot = "$PSScriptRoot\..\outputs\primitive_mesh_cpp_official_scope_strengths_001",
    [int]$MaxParallelModels = 13
)

$ErrorActionPreference = "Stop"
$culture = [System.Globalization.CultureInfo]::InvariantCulture
$modelIds = @(2, 3, 4, 5, 12, 13, 14, 15, 16, 17, 18, 19, 20)
$executablePath = (Resolve-Path -LiteralPath $Executable).Path
$inputPath = (Resolve-Path -LiteralPath $InputRoot).Path
$outputPath = [System.IO.Path]::GetFullPath($OutputRoot)
$modelsPath = Join-Path $outputPath "models"
New-Item -ItemType Directory -Path $modelsPath -Force | Out-Null

if ($MaxParallelModels -lt 1) { throw "MaxParallelModels must be positive" }

# Model 2 has already been generated by the same current C++ implementation.
# Referencing it avoids duplicating roughly 101 complete OBJ result sets.
$externalModel2Root = "/outputs/primitive_mesh_cpp_model2_strengths_002"
$nextStrength = @{}
foreach ($modelId in $modelIds) {
    if ($modelId -eq 2) { continue }
    $firstMissing = 101
    foreach ($index in 0..100) {
        $metadata = Join-Path $modelsPath ("{0}\s{1:D3}\model.json" -f $modelId, $index)
        if (-not (Test-Path -LiteralPath $metadata)) {
            $firstMissing = $index
            break
        }
    }
    $nextStrength[$modelId] = $firstMissing
}

$running = @{}
$startedAt = Get-Date
while ($true) {
    $activeModels = [System.Collections.Generic.HashSet[int]]::new()
    foreach ($job in $running.Values) { [void]$activeModels.Add($job.ModelId) }
    foreach ($modelId in $modelIds) {
        if ($modelId -eq 2 -or $running.Count -ge $MaxParallelModels) { continue }
        if ($activeModels.Contains($modelId) -or $nextStrength[$modelId] -gt 100) { continue }
        while ($nextStrength[$modelId] -le 100) {
            $existing = Join-Path $modelsPath `
                ("{0}\s{1:D3}\model.json" -f $modelId, $nextStrength[$modelId])
            if (-not (Test-Path -LiteralPath $existing)) { break }
            $nextStrength[$modelId]++
        }
        if ($nextStrength[$modelId] -gt 100) { continue }
        $index = $nextStrength[$modelId]
        $directory = Join-Path $modelsPath ("{0}\s{1:D3}" -f $modelId, $index)
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
        $strength = ($index / 100.0).ToString("0.00", $culture)
        $arguments = @(
            "--input", (Join-Path $inputPath "$modelId.obj"),
            "--output-dir", $directory,
            "--primitive-types", "polygon,frustum",
            "--cone-segments", "24",
            "--analysis-strength", $strength
        )
        $process = Start-Process -FilePath $executablePath -ArgumentList $arguments `
            -RedirectStandardOutput (Join-Path $directory "analysis.stdout.txt") `
            -RedirectStandardError (Join-Path $directory "analysis.stderr.txt") `
            -WindowStyle Hidden -PassThru
        $running[$process.Id] = [pscustomobject]@{
            Process = $process
            ModelId = $modelId
            Index = $index
            Directory = $directory
        }
    }

    if ($running.Count -eq 0) { break }
    Start-Sleep -Milliseconds 250
    foreach ($processId in @($running.Keys)) {
        $job = $running[$processId]
        if (-not $job.Process.HasExited) { continue }
        $job.Process.WaitForExit()
        $metadata = Join-Path $job.Directory "model.json"
        if (-not (Test-Path -LiteralPath $metadata)) {
            $errorText = Get-Content (Join-Path $job.Directory "analysis.stderr.txt") -Raw
            throw "Model $($job.ModelId), strength $($job.Index) failed: $errorText"
        }
        $nextStrength[$job.ModelId] = $job.Index + 1
        $running.Remove($processId)
        $elapsed = [math]::Round(((Get-Date) - $startedAt).TotalSeconds, 1)
        Write-Output "model=$($job.ModelId) completed_strength=$($job.Index) elapsed_seconds=$elapsed"
    }
}

$variants = foreach ($modelId in $modelIds) {
    foreach ($index in 0..100) {
        if ($modelId -eq 2) {
            $metadata = "$externalModel2Root/s$($index.ToString('D3'))/model.json"
        } else {
            $metadata = "models/$modelId/s$($index.ToString('D3'))/model.json"
        }
        [ordered]@{
            model_id = $modelId
            strength = $index / 100.0
            metadata = $metadata
        }
    }
}
$models = foreach ($modelId in $modelIds) {
    if ($modelId -eq 2) {
        $metadata = "$externalModel2Root/s040/model.json"
    } else {
        $metadata = "models/$modelId/s040/model.json"
    }
    [ordered]@{ id = $modelId; metadata = $metadata }
}
$manifest = [ordered]@{
    algorithm = "CppHierarchicalPrimitiveMeshAnalysis"
    complete = $true
    model_count = $modelIds.Count
    models = @($models)
    strength_variants = @($variants)
}
$manifest | ConvertTo-Json -Depth 5 | Set-Content `
    -LiteralPath (Join-Path $outputPath "viewer_manifest.json") -Encoding ASCII
Write-Output "manifest=$(Join-Path $outputPath 'viewer_manifest.json')"
